/**
 * Product-page ingredient label → production IMAGES path (exact webp filenames).
 * Keep in sync with `ingredients` in Ingredients.tsx and files on the server.
 */
export const INGREDIENT_IMAGE_MAP: Record<string, string> = {
  'blue tea': '/IMAGES/blue pea.webp',
  aprajita: '/IMAGES/blue pea.webp',
  'blue pea': '/IMAGES/blue pea.webp',
  charcoal: '/IMAGES/charcoal.webp',
  'activated charcoal': '/IMAGES/charcoal.webp',
  yuja: '/IMAGES/yuja.webp',
  citron: '/IMAGES/yuja.webp',
  papaya: '/IMAGES/papaya.webp',
  'shea butter': '/IMAGES/shea butter.webp',
  'coconut oil': '/IMAGES/coconut-oil.webp',
  coconut: '/IMAGES/coconut-oil.webp',
  mulberry: '/IMAGES/mulberry.webp',
  grapeseed: '/IMAGES/grapeseed.webp',
  'grape seed': '/IMAGES/grapeseed.webp',
  'aha & bha': '/IMAGES/AHA & BHA.webp',
  aha: '/IMAGES/AHA & BHA.webp',
  bha: '/IMAGES/AHA & BHA.webp',
  'alpha hydroxy acid': '/IMAGES/AHA & BHA.webp',
  'beta hydroxy acid': '/IMAGES/AHA & BHA.webp',
  amla: '/IMAGES/Amla.webp',
  'indian gooseberry': '/IMAGES/Amla.webp',
  'argan oil': '/IMAGES/Argan Oils.webp',
  'argan oils': '/IMAGES/Argan Oils.webp',
  biotin: '/IMAGES/Biotin.webp',
  blueberry: '/IMAGES/Blueberry.webp',
  brahmi: '/IMAGES/Brahmi.webp',
  flaxseed: '/IMAGES/Flaxseed.webp',
  'flax seed': '/IMAGES/Flaxseed.webp',
  'green tea': '/IMAGES/Green Tea.webp',
  'juniper berry': '/IMAGES/Juniper Berry.webp',
  'kakadu plum': '/IMAGES/Kakadu Plum.webp',
  'kale leaf': '/IMAGES/Kale Leaf.webp',
  kale: '/IMAGES/Kale Leaf.webp',
  'kaolin clay': '/IMAGES/Kaolin Clay.webp',
  kaolin: '/IMAGES/Kaolin Clay.webp',
  mustard: '/IMAGES/Mustard.webp',
  'olive squalane': '/IMAGES/Olive Squalane.webp',
  squalane: '/IMAGES/Olive Squalane.webp',
  palmetto: '/IMAGES/saw palmetto.webp',
  'saw palmetto': '/IMAGES/saw palmetto.webp',
  quinoa: '/IMAGES/Quinoa.webp',
  'rice powder': '/IMAGES/Rice Powder.webp',
  saffron: '/IMAGES/Saffron.webp',
  sesame: '/IMAGES/Sesame.webp',
  'sesame seed': '/IMAGES/Sesame.webp',
  'tapioca starch': '/IMAGES/Tapioca Starch.webp',
  tapioca: '/IMAGES/Tapioca Starch.webp',
  'tea tree': '/IMAGES/Tea Tree.webp',
  'tea tree oil': '/IMAGES/Tea Tree.webp',
  'vitamin c & b5': '/IMAGES/Vitamin C & B5.webp',
  'vitamin c': '/IMAGES/Vitamin C & B5.webp',
  'vitamin b5': '/IMAGES/Vitamin C & B5.webp',
  'pantothenic acid': '/IMAGES/Vitamin C & B5.webp',
  'white tea': '/IMAGES/white tea.webp',
  'yellow dragon': '/IMAGES/Yellow Dragon.webp',
  'c13-14 isoparaffin': '/IMAGES/C13-14 Isoparaffin.webp',
  isoparaffin: '/IMAGES/C13-14 Isoparaffin.webp',
  'rose extract': '/IMAGES/rose extract ROS.webp',
  'rose extract ros': '/IMAGES/rose extract ROS.webp',
  'almond oil': '/IMAGES/almond oil.webp',
  almond: '/IMAGES/almond oil.webp',
  'centella asiatica': '/IMAGES/centella asiatica.webp',
  centella: '/IMAGES/centella asiatica.webp',
  cica: '/IMAGES/centella asiatica.webp',
  'fenugreek oil': '/IMAGES/fenugreek oil.webp',
  fenugreek: '/IMAGES/fenugreek oil.webp',
  chamomile: '/IMAGES/Chamomile.webp',
  'ylang ylang': '/IMAGES/ylang ylang.webp',
  ylang: '/IMAGES/ylang ylang.webp',
  glycerin: '/IMAGES/Glycerin.webp',
  glycerol: '/IMAGES/Glycerin.webp',
}
